### ISSUE TITLE
Too long title crashes the program

### ISSUE THREAD

**Issue by SashLilac** [MyPasswordIsWeak/lilacDL-DLer#1]
At the end of the program, having too long of a title in the .lilacDL file crashes with:

`(node:8696) UnhandledPromiseRejectionWarning: Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:634:37)
    at Buffer.toString (buffer.js:804:14)
    at Object.readFileSync (fs.js:408:41)
    at fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at ErrorHandler.<anonymous> (C:\snapshot\lilacDL-DLer-master\lilacDL.js:127:45)
    at Object.onceWrapper (events.js:421:28)
    at ErrorHandler.emit (events.js:315:20)
    at ErrorHandler.start (C:\snapshot\lilacDL-DLer-master\errors.js:25:25)
    at C:\snapshot\lilacDL-DLer-master\lilacDL.js:148:22
    at runMicrotasks (<anonymous>)
(Use `lilacdl-win --trace-warnings ...` to show where the warning was created)
(node:8696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by SashLilac** [comment]
It's not the length. Further testing done.

**Comment by SashLilac** [comment]
Temporary fix: `lilacdl-(platform) /path/to/file.lilacDL --no-final-md5-check`

**Comment by SashLilac** [comment]
Fixed in v1.1.0.
