### ISSUE TITLE
Error "(file part) can not be found)"

### ISSUE THREAD

**Issue by TimmSkiller** [MyPasswordIsWeak/lilacDL-DLer#3]
Shows this error when all parts are downloaded:
```
(node:10669) UnhandledPromiseRejectionWarning: Error: # ENOENT: no such file or directory, open '/storage/emulated/0/lilacDL-DLer//.data/temp/z192_-_Nintendo_Video_(Europe)_(eShop).3dsz192_-_Nintendo_Video_(Europe)_(eShop).3ds.0'
    at Object.openSync (fs.js:465:3)
    at readFileSync (fs.js:368:35)
    at ErrorHandler.<anonymous> (/storage/emulated/0/lilacDL-DLer/src/lilacDL.js:118:54)
    at Object.onceWrapper (events.js:420:28)
    at ErrorHandler.emit (events.js:314:20)
    at ErrorHandler.start (/storage/emulated/0/lilacDL-DLer/src/Util/errors.js:25:25)
    at /storage/emulated/0/lilacDL-DLer/src/lilacDL.js:156:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

A "/" is missing in the file path, it seems.

**Comment by MyPasswordIsWeak** [comment]
Fixed in latest commit
